# Generated by Django 6.0 on 2025-12-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Cantidad disponible en la unidad base de consumo', max_digits=12),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad en unidad base del ingrediente', max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_receta', to='inventory.producto')),
            ],
            options={
                'unique_together': {('producto', 'ingrediente')},
            },
        ),
    ]
