# Generated by Django 5.2.7 on 2025-11-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_um', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_um', models.CharField(max_length=50)),
                ('abreviacion_um', models.CharField(max_length=5)),
                ('tipo_um', models.CharField(choices=[('Volumen', 'Volumen'), ('Peso', 'Peso'), ('Unidad', 'Unidad')], max_length=20)),
                ('es_unidad_base', models.BooleanField(default=False)),
                ('factor_conversion', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ingrediente', models.CharField(max_length=50)),
                ('tipo_articulo', models.CharField(choices=[('INSUMO_RECETA', 'Insumo de Receta'), ('EMPAQUE', 'Empaque'), ('CONDIMENTO_INCLUIDO', 'Condimento Incluido')], max_length=20)),
                ('unidad_base_consumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes_consumo', to='inventory.unidadmedida')),
                ('unidad_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes_compra', to='inventory.unidadmedida')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ingrediente',
            },
        ),
    ]
