# Generated by Django 5.2.7 on 2025-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_unit_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('cocina', 'cocina'), ('reparto', 'reparto'), ('ensamble', 'ensamble'), ('supervisor', 'supervisor'), ('admin', 'Administrador')], max_length=20),
        ),
    ]
