# Generated by Django 5.2.7 on 2025-10-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario')], max_length=10)),
                ('tenant_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_pin', models.CharField(max_length=6, unique=True)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_alias', models.CharField(blank=True, max_length=50, null=True)),
                ('kitchen_id', models.IntegerField()),
            ],
        ),
    ]
